version: "3.8"
services:
  accounts-frontend:
    container_name: accounts-frontend
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 4200:80
    volumes:
      - ./:/usr/local/app/frontend
    command: nginx -g "daemon off;"
